### ISSUE TITLE
background.colorOverlay property for PVA is not working

### ISSUE THREAD

**Issue by dominik-meissner** [alexa-smart-properties/skill-sample-for-nodejs-hospitality#6]
In your Postman Sample Payload "PVA - Room Service Rating" you are setting the `background.colorOverlay` property to false. According to the documentation (https://developer.amazon.com/en-US/docs/alexa/alexa-smart-properties/notifications-api.html#persistent-visual-alert-templates) this should remove the scrim from the background image. Unfortunately in my testing this is not the case.

**Comment by kenhsu001** [comment]
Thanks Dominik for the feedback, the optionsList template is under going some additional changes and I have alerted the product team about this issue.

**Comment by kenhsu001** [comment]
resolved
